name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.3"
      - uses: leafo/gh-actions-luarocks@v4
      - name: Install dependencies
        run: |
          luarocks make usl4l-0.1.0-1.rockspec
      - name: Install Luacheck
        run: |
          luarocks install luacheck
      - name: Lint
        run: |
          luacheck lua bin
      - name: Run Unit Tests
        run: |
          lua tests/model_test.lua
          lua tests/measurement_test.lua
          lua tests/parser_test.lua
      - name: Run CLI Tests
        run: |
          ./tests/cli_test.sh